<?php

/**
 * @file
 * Hook implementations and callbacks for the campaignion_csv mdule.
 */

use Drupal\campaignion_csv\DirectoryManager;
use Drupal\campaignion_csv\Exporter\WebformGeneric\Exporter as WebformExporter;
use Drupal\campaignion_csv\Exporter\ContactExporter;
use Drupal\campaignion_csv\Exporter\ActivityExporter;
use Drupal\campaignion_csv\Files\MonthlyFilePattern;
use Drupal\campaignion_csv\Files\SingleFilePattern;

/**
 * Implements hook_cronapi().
 */
function campaignion_csv_cronapi() {
  $items['campaignion_csv_cron'] = array(
    'description' => 'Update exported files.',
    'rule' => '0+@ 0 * * *',
    'weight' => 100,
    'callback' => 'campaignion_csv_cron',
  );
  return $items;
}

/**
 * Cron callback: Update exported files.
 */
function campaignion_csv_cron() {
  DirectoryManager::fromConfig()->build();
}

/**
 * Implements hook_campaignion_csv_info().
 */
function campaignion_csv_campaignion_csv_info() {
  $export['actions_monthly'] = [
    'file_pattern' => [
      'class' => MonthlyFilePattern::class,
      'path' => 'actions/%Y-%m.csv',
      'retention_period' => new \DateInterval('P6M'),
      'refresh_interval' => new \DateInterval('PT23H30M'),
    ],
    'exporter' => [
      'class' => WebformExporter::class,
      'actions' => TRUE,
      'donations' => FALSE,
    ],
  ];
  $export['donations_monthly'] = [
    'file_pattern' => [
      'class' => MonthlyFilePattern::class,
      'path' => 'donations/%Y-%m.csv',
      'retention_period' => new \DateInterval('P6M'),
      'refresh_interval' => new \DateInterval('PT23H30M'),
    ],
    'exporter' => [
      'class' => WebformExporter::class,
      'actions' => FALSE,
      'donations' => TRUE,
    ],
  ];
  $export['contacts'] = [
    'file_pattern' => [
      'class' => SingleFilePattern::class,
      'path' => 'contacts.csv',
      'refresh_interval' => new \DateInterval('PT23H30M'),
    ],
    'exporter' => [
      'class' => ContactExporter::class,
      'bundle' => 'contact',
    ],
  ];
  $export['activities_monthly'] = [
    'file_pattern' => [
      'class' => MonthlyFilePattern::class,
      'path' => 'activities/%Y-%m.csv',
      'retention_period' => new \DateInterval('P6M'),
      'refresh_interval' => new \DateInterval('PT23H30M'),
    ],
    'exporter' => [
      'class' => ActivityExporter::class,
    ],
  ];
  return $export;
}
