<?php

/**
 * @file
 * Hook implementations and callbacks for the campaignion_csv mdule.
 */

use Drupal\campaignion_csv\FilePattern\Monthly;
use Drupal\campaignion_csv\FilePattern\SingleFile;
use Drupal\campaignion_csv\WebformGeneric\Exporter as WebformExporter;
use Drupal\campaignion_csv\ExporterFactory;
use Drupal\campaignion_csv\TimeframeExporterFactory;
use Drupal\campaignion_csv\ContactExporter;
use Drupal\campaignion_csv\ActivityExporter;

/**
 * Implements hook_campaignion_csv_info().
 */
function campaignion_csv_campaignion_csv_info() {
  $export['actions_monthly'] = [
    'file_pattern' => [
      'class' => Monthly::class,
      'path' => 'actions/%Y-%m.csv',
      'retention_period' => new \DateInterval('P6M'),
      'refresh_interval' => new \DateInterval('PT23H30M'),
    ],
    'exporter' => [
      'class' => WebformExporter::class,
      'factory_class' => TimeframeExporterFactory::class,
      'actions' => TRUE,
      'donations' => FALSE,
    ],
  ];
  $export['donations_monthly'] = [
    'file_pattern' => [
      'class' => Monthly::class,
      'path' => 'donations/%Y-%m.csv',
      'retention_period' => new \DateInterval('P6M'),
      'refresh_interval' => new \DateInterval('PT23H30M'),
    ],
    'exporter' => [
      'class' => WebformExporter::class,
      'factory_class' => TimeframeExporterFactory::class,
      'actions' => FALSE,
      'donations' => TRUE,
    ],
  ];
  $export['contacts'] = [
    'file_pattern' => [
      'class' => SingleFile::class,
      'path' => 'contacts.csv',
      'refresh_interval' => new \DateInterval('PT23H30M'),
    ],
    'exporter' => [
      'class' => ContactExporter::class,
      'factory_class' => ExporterFactory::class,
      'bundle' => 'contact',
    ],
  ];
  $export['activities_monthly'] = [
    'file_pattern' => [
      'class' => Monthly::class,
      'path' => 'activities/%Y-%m.csv',
      'retention_period' => new \DateInterval('P6M'),
      'refresh_interval' => new \DateInterval('PT23H30M'),
    ],
    'exporter' => [
      'class' => ActivityExporter::class,
      'factory_class' => TimeframeExporterFactory::class,
    ],
  ];
  return $export;
}
